# Generated by Django 4.1 on 2022-12-27 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Create', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile_no',
            field=models.IntegerField(null=True),
        ),
    ]
